services:
  cm:
    cap_add:
      - SYS_TIME
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - utility
                - compute
                - video
              driver: nvidia
              count: -1
    image: cm #ghcr.io/kjenney/cm-pkg:main
    network_mode: host
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      - type: bind
        source: "$PWD/snapshot.yaml"
        target: /snapshot.yaml
      # Bind models externally - override to a directory that exists or comment out
      #- type: bind
      #  source: /home/ken/share/diffusion/models
      #  target: /usr/src/ComfyUI/models
      # Bind workflows externally - override to a directory that exists or comment out 
      #- type: bind
      #  source: /home/ken/share/diffusion/workflows
      #  target: /usr/src/ComfyUI/user/default/workflows
      #- type: bind
      #  source: /home/ken/share/diffusion/input
      #  target: /usr/src/ComfyUI/input
      #- type: bind
      #  source: /home/ken/share/diffusion/output
      #  target: /usr/src/ComfyUI/output
