services:
  cm:
    cap_add:
      - SYS_TIME
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - utility
                - compute
                - video
              driver: nvidia
              count: -1
    image: ghcr.io/kjenney/cm-pkg:hunyuan_video_wrapper
    network_mode: host
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      - type: bind
        source: "$PWD/snapshot.json"
        target: /snapshot.json
      - type: bind
        source: /home/ken/share/diffusion/models
        target: /usr/src/ComfyUI/models
      - type: bind
        source: /home/ken/share/diffusion/workflows
        target: /usr/src/ComfyUI/user/default/workflows
