services:
  cm:
    cap_add:
      - SYS_TIME
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - utility
                - compute
                - video
              driver: nvidia
              count: -1
    image: ghcr.io/kjenney/cm-pkg:v0.10
    network_mode: host
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      - type: bind
        source: /tmp/snapshot.yaml
        target: /snapshot.yaml
