services:
  cm:
    cap_add:
      - SYS_TIME
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - utility
                - compute
                - video
              driver: nvidia
              count: -1
    image: ghcr.io/kjenney/cm-pkg:main
    network_mode: host
    runtime: nvidia
    ports:
      - "8188:8188"
    volumes:
      # Optioal - uncomment when you have a snapshot to restore
      - type: bind
        source: "$PWD/snapshot.yaml"
        target: /snapshot.yaml
      # Optioal - uncomment when you have a snapshot to restore
      #- type: bind
      #  source: "$PWD/snapshot.json"
      #  target: /snapshot.json
      # Bind models externally - override to a directory that exists or comment out
      - type: bind
        source: /home/ken/share/diffusion/models
        target: /usr/src/ComfyUI/models
      # Bind workflows externally - override to a directory that exists or comment out 
      - type: bind
        source: /home/ken/share/diffusion/workflows
        target: /usr/src/ComfyUI/user/default/workflows
