name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - '**/*.dockerfile'
      - '.github/workflows/docker-publish.yml'
      - '**/*'

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build \
            --tag ghcr.io/${{ github.repository }}/my-image:latest .

      # Push the Docker image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-image:latest

